# run this at the start of each new PS session

# local cache of raw zip files as generated by Salesforce Weekly Extract job
$zipRoot = "$env:OneDriveCommercial\WE"

# the latest zip filenames all start with this string
$zipFileStem = "$zipRoot\WE_00D80000000KHPpEAO_" # this stem will change with each new batch

# general work folder (not sync'd to cloud SPO)
$downloads = "$env:USERPROFILE\Downloads"

# for the unzipped files before renaming & moving
$unzippedRoot = "$env:USERPROFILE\Downloads"

# qualified files will be renamed and moved into one of the SPO doclibs: S0, S1, ... S5 
$outRoot = $env:OneDriveCommercial 

# other files will be moved to a 'discard' folder
$skipFolder = "$unzippedRoot\Skipped"

# load the map into session memory (hashing takes several minutes)
$map = Import-Csv -Path "$downloads\qryAttachmentScope.csv" | 
#    Select -First 100 |
    Group -AsHashTable -Property Id  # retain in memory as a dictionary

$map.Count # 33498 - should agree with source query in Access

